AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  FunctionName:
    Type: String
    Default: LastKeypair
  FunctionKmsAuthName:
    Type: String
    Default: LastKeypair
  KeyAliasName:
    Type: String
    Default: alias/LastKeypair
  PstoreCAKeyBytesName:
    Type: String
  S3Bucket:
    Type: String
  S3Key:
    Type: String
  S3ObjectVersion:
    Type: String
  MFARequired:
    Type: String
    Default: false
  AllowedAwsAccounts:
    Type: String
Conditions:
  MFARequired: !Equals [!Ref MFARequired, "true"]
Resources:
  Key:
    Type: AWS::KMS::Key
    Properties:
      KeyPolicy:
        Version: "2012-10-17"
        Id: key-policy
        Statement:
          - Sid: Default
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:role/KMSAdminRole
#              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: kms:*
            Resource: "*"
          - Sid: KmsDescribe
            Effect: Allow
            Principal:
              AWS: !Split [",", !Ref AllowedAwsAccounts]
            Action: kms:DescribeKey
            Resource: "*"
          - Sid: AllowIAMUserEncrypt
            Effect: Allow
            Principal:
              AWS: !Split [",", !Ref AllowedAwsAccounts]
            Action: kms:Encrypt
            Resource: "*"
            Condition:
              StringEquals:
                kms:EncryptionContext:to: !Ref FunctionKmsAuthName
                kms:EncryptionContext:type: "${aws:principaltype}"
                kms:EncryptionContext:fromId: "${aws:userid}"
                kms:EncryptionContext:fromAccount: "${kms:CallerAccount}"
              StringEqualsIfExists:
                aws:username: "${kms:EncryptionContext:fromName}"
                kms:EncryptionContext:fromName: "${aws:username}"
                ec2:SourceInstanceARN: "${kms:EncryptionContext:hostInstanceArn}"
                kms:EncryptionContext:hostInstanceArn: "${ec2:SourceInstanceARN}"
#              Bool:
#                aws:MultiFactorAuthPresent: true
          - Sid: KmsLambdaAuth
            Effect: Allow
            Principal:
              AWS: !GetAtt LambdaRole.Arn
            Action: kms:Decrypt
            Resource: "*"
            Condition:
              StringEquals:
                kms:EncryptionContext:to:
                  - !Ref FunctionKmsAuthName
  KeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      TargetKeyId: !Ref Key
      AliasName: !Ref KeyAliasName
  Function:
    Type: AWS::Lambda::Function
    Properties:
      Handler: handler.Handle
      FunctionName: !Ref FunctionName
      Role: !GetAtt LambdaRole.Arn
      Runtime: python2.7
      Timeout: 60
      Code:
        S3Bucket: !Ref S3Bucket
        S3Key: !Ref S3Key
        S3ObjectVersion: !Ref S3ObjectVersion
      Environment:
        Variables:
          KMS_KEY_ID: !GetAtt Key.Arn
          KMS_TOKEN_IDENTITY: !Ref FunctionKmsAuthName
          VALIDITY_DURATION: 900
          PSTORE_CA_KEY_BYTES: !Ref PstoreCAKeyBytesName
          AUTHORIZATION_LAMBDA: !Ref AuthorizationFunction
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies: []
  Policy: # needed to avoid circular dependency between function, role and key
    Type: AWS::IAM::Policy
    Properties:
      Roles: [!Ref LambdaRole]
      PolicyName: root
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*
          - Effect: Allow
            Action: ssm:GetParameters
            Resource: "*"
          - Effect: Allow
            Action: kms:Decrypt
            Resource: "*"
          - Effect: Allow
            Action: lambda:InvokeFunction
            Resource: !GetAtt AuthorizationFunction.Arn
          - Effect: Allow
            Action: kms:Describe*
            Resource: !GetAtt Key.Arn
  AuthorizationFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      FunctionName: !Sub ${FunctionName}-Authorizer
      Role: !GetAtt LambdaRole.Arn
      Runtime: nodejs6.10
      Timeout: 60
      Code:
        ZipFile: |
          exports.handler = function(event, context, callback) {
            console.log(JSON.stringify(event));
            var cb = function(err, resp) {
              console.log(JSON.stringify(resp));
              callback(err, resp);
            }
            if (event.RemoteInstanceArn == "abcdef") {
              cb(null, {authorized: true});
            } else if (event.Vouchers && event.Vouchers.length > 0) {
              cb(null, {
                authorized: true,
                jumpbox: {
                  ipAddress: "12.34.56.78",
                  instanceId: "abcdef",
                  user: event.Vouchers[0].Name // really just for testing purposes
                }
              });
            } else {
              cb(null, {
                authorized: true,
                jumpbox: {
                  ipAddress: "12.34.56.78",
                  instanceId: "abcdef",
                  user: "ec2-user"
                }
              });
            }
          };
Outputs:
  FunctionArn:
    Value: !GetAtt Function.Arn
  KeyArn:
    Value: !GetAtt Key.Arn
